export const ROUTES = {
  anketa1: "/anketa-1",
  anketa10: "/anketa-10",
  anketa11: "/anketa-11",
  anketa12: "/anketa-12",
  anketa2: "/anketa-2",
  anketa3: "/anketa-3",
  anketa4: "/anketa-4",
  anketa5: "/anketa-5",
  anketa6: "/anketa-6",
  anketa7: "/anketa-7",
  anketa8: "/anketa-8",
  anketa9: "/anketa-9",
  auth: "/auth",
  chat: "/chat",
  chatProfile: "/chat/:chatId/profile",
  chatRoom: "/chat/:chatId",
  components: "/components",
  feed: "/feed",
  filters: "/filters",
  likeProfile: "/likes/:profileId",
  likes: "/likes",
  nearby: "/nearby",
  nearbyProfile: "/nearby/:profileId",
  numberVerification: "/number-verification",
  profile: "/profile",
  profileAbout: "/profile/about",
  profileAddContactManually: "/profile/add-contact",
  profileGuidelines: "/profile/guidelines",
  profileHideFromContacts: "/profile/hide-from-contacts",
  profileNotifications: "/profile/notifications",
  profilePrivacy: "/profile/privacy",
  profileSettings: "/profile/settings",
  profileSupport: "/profile/support",
  wallet: "/wallet",
  welcome: "/welcome",
} as const;

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES];
